### PR TITLE
main: allow multiple breakpoints to be specified

### PR DESCRIPTION
**Pull request by cocus**
As a side effect, the step-over "next address breakpoint" gets another variable to store it, rather than reusing the main code breakpoint address.

### CODE REVIEW

**Comment by mfld-fr** [comment]
OK for me, just waiting @ghaerr feedback as he was the one who asked for multiple breakpoints.

**Comment by ghaerr** [comment]
Looks great, thank you @cocus!

**Comment by cocus** [comment]
I might add this feature into the stdio debug console, so we can write ```b <address>```. I think the 8 char buffer should be enouhg to hold a full logical address and two additional chars ('b' and ' ').

**Comment by ghaerr** [comment]
> I might add this feature into the stdio debug console, so we can write b <address>. 

That would be great!

Actually, it would be nice if the command line parameters which also are duplicated in debug console were handled by the same code, rather than duplicating it. Of course, the character used for the command line argument and the character used for the debug console may not be the same. Thus, I think even more reorganization in emu-main.c is needed.

> I think the 8 char buffer should be enouhg to hold a full logical address and two additional chars ('b' and ' ').

Just increase the buffer size.

**Pull request merged**
