### PR TITLE
Merge 'next' branch into 'master'

### PR DESCRIPTION
**Pull request by mfld-fr**

### CODE REVIEW

**Comment by mfld-fr** [comment]
While testing this branch on several targets & configurations before merging it into `master`, I got a regression with the latest ELKS built with `emu86-disk.config` / EMU86 built with `config-elks.mk`:
```
VFS: Unable to open root device 0380
```

Everything is OK with ELKS built with `emu86-rom.config`, also with Advantech (MON86 & SYS86) and PC/XT/AT ('8086tiny' floppy image).

**Comment by ghaerr** [comment]
> I got a regression with the latest ELKS built with emu86-disk.config / EMU86 built with config-elks.mk:

Some cleanup changes were made to ELKS yesterday. These changes work under QEMU, but cause EMU86 to fail on last commit to master 80fc8702486ae9144c6a1cbd5845e87052d6c2c7 (No fatal from ROM protection). So it looks like the problem has not to do with merge next to master but before that.

I will look into it and do code review on this merge.

**Comment by ghaerr** [comment]
Working from last commit to master 80fc8702486ae9144c6a1cbd5845e87052d6c2c7, EMU96 shows BIOS INT 13h result of 0 floppy drives, while QEMU shows 1 floppy drive. So problem is very likely in modified BIOS INT 13h handler from previous commit:
Screen Shot 2021-05-14 at 8 46 52 AM
This is why ELKS can't open root device, as no floppy is present.

**Comment by ghaerr** [comment]
Review complete, OK to merge. There's quite a lot of changes we've made in the last few days!

I hadn't noticed that MSDOS samples the BIOS timer at boot: why exactly is it we need to emulate the BDA timer?

It seems that the BDA emulation is never ending... we now have BDA initialization in multiple places.

Also, why is timer_enabled turned on initially in timer-elks.c? Just curious.

**Comment by mfld-fr** [comment]
Thanks for the review and the debug !

MSDOS uses the BIOS timer to timeout and exit from a wait loop during the boot.

**Comment by ghaerr** [comment]
> Also, why is timer_enabled turned on initially in timer-elks.c? Just curious.

Having the timer turned on initially seems to work for now for ELKS, but I thought it was determined that an early timer interrupt could cause kernel panic. FYI. It was never determined whether the problem was the result of timer frequency only, or whether just that timer was enabled prior to ELKS boot. I realize that BIOS may have initialized timer prior to ELKS boot, thus my continuing confusion on this. 

Was this turned on because MSDOS needs it for BIOS timer?

**Comment by mfld-fr** [comment]
Because the BIOS INT 08h was missing a PUSH AX / POP AX before 58c22f3, it was likely to crash ELKS at any time. Now that the AX register is saved properly, the BIOS timer can be started before ELKS boot.

**Comment by ghaerr** [comment]
Geez, amazing we never saw AX trashing in handler until now. Also somewhat amazing ELKS never crashed from timer interrupt except at early boot.

Good to know ELKS has neither kernel crash problem nor problem with "fast" timers.

**Pull request merged**
