### PR TITLE
[rom] Implement some BIOS services

### PR DESCRIPTION
**Pull request by cocus**
Implements int10h 0,1,7; int13h 4, 0x15; int14h 0; int16h 2; int17h 1;
int1ah 2, 4.
MS-DOS 6.22 boots to an A:\> prompt!

### CODE REVIEW

**Comment by cocus** [comment]
Well, the build error comes when trying to fetch an outdated (I think) package? Maybe there's something missing in the action to do a fetch? Or the repos are outdated somehow.

**Comment by ghaerr** [comment]
Hello @cocus,

Wow, you've added quite a few new enhancements to the ROM BIOS, as well as some non- or partially-implemented ones. Nice work getting MSDOS to boot!

I am thinking that perhaps this entire PR should be contributed as a seperate rom-pc.c, instead of changes to rom-elks.c, at least for now. The reasons for this are:
- It is very useful to keep the size of the ELKS ROM emulation smaller, as it is then more easily seen exactly what ELKS needs, versus MSDOS, which seems to require quite a few more entry points in order to function. Myself, I am using EMU86 to prove exactly what external devices and BIOS functions are required, and the less the better, for ELKS.
- I worry a bit about adding partially-implemented functions, e.g. read time/date from RTC, as then these functions may seem to work, but in fact are not correct. For MSDOS, no big deal, but for ELKS, different matter.
- I am in the middle of trying to get PR #50 approved, and we're changing the same file rom-elks.c. It could be a lot of extra work for both of us to ensure correctness, especially for more complex PRs.

If these changes were to temporarily be committed as entirely as a new 'rom-pc.c', then you could work separately on it until it works well, and IMO the EMU86 project could gain another target: generic PC (rather than just ELKS). On a longer term basis, the files could be diff'd, or perhaps even the BIOS INT functions could be kept in seperate files and gathered together in some way. Just some thoughts.

@mfld-fr will have to be the decider for what to do. Let us see what he wants. 

Thank you very much for this contribution!

**Comment by cocus** [comment]
Yeah, I can migrate this to a "generic pc" architecture rom file, even tho it's going to be really minimalistic, since I don't want to have all the whistles as a fully fledged PC emulator (particularly because I want to use whatever I'm running on my 80C188 board, and it's going to be difficult, almost impossible, to emulate a PC properly).

**Comment by ghaerr** [comment]
Well, perhaps "pc" or "generic pc" isn't the right name for it. Lets see what @mfld-fr wants to do before you change it. Perhaps a discussion about targets is in order.

Thanks!

**Comment by mfld-fr** [comment]
Build error gone after retrying the pipe, looks like a GitHub transient failure.

**Comment by mfld-fr** [comment]
@cocus : please copy the existing rom-elks.c to a new rom-or556.c (same name as your TARGET), and add your improvements in that latest, so @ghaerr could still manage the ELKS dependencies on the BIOS.

We will consider a more generic PC BIOS support when the dust would have settle a bit...

**Comment by mfld-fr** [comment]
Related to issue #30

**Comment by mfld-fr** [comment]
Please hold on this PR, I am picking the changes from it to #56

**Comment by mfld-fr** [comment]
Changes picked and superseded by #56

**Pull request closed without merging**
