### PR TITLE
Add trace filter and PC/XT/AT target

### LINKED ISSUE #30: MSDOS or FreeDOS does not boot under EMU86
Hi, I've hacked this project enough to support my weird board that I'm trying to use (80C188, 128k RAM, 512k FLASH, serial port, and I've added an SD card) so I don't have to remove the flash, burn it, and place it back on the board to test my code. Of course I'm not emulating all of the aspects of the 80C188, but close enough.
I've reached a point where my custom bios is able to provide enough system services to interact with the user, read disk, etc. 
Now I've tried to boot my own code, and it works perfectly. After that, I've tried to run DOS (MS-DOS 3.30, MS-DOS 6.22, FreeDOS) all of them from a 1.4MB floppy (emulated), but there's always an issue and it crashes. I'm not sure why tho, debugging it doesn't yield anything obvious. Both the MS DOS 3.30 and 6.22 usually crash after the DOS has been set up so it's providing the int21h, and I can see that it overwrites the entire BDA with gibberish.
Maybe you have some experiences running DOS on the emulator, or maybe one of my changes did break something, or even my BIOS is faulty or it's providing something that the DOS doesn't like.

Thanks!

### PR DESCRIPTION
**Pull request by mfld-fr**
* Add filter to trace instruction once, to reduce the trace flow and thus helping to figure out the code path that leads to an error,
* Add a distinct target for more generic PC/XT/AT, to keep ELKS target under strict dependency control,
* Fork the ELKS BIOS to a generic PC/XT/AT BIOS (will regroup common code after stabilization),
* Add the needed BIOS functions for MSDOS and FreeDOS boot & prompt.

Closes #30

### CODE REVIEW

**Comment by ghaerr** [comment]
@mfld-fr : Lots of nice changes in this PR :) 

Having a "reference" BIOS is a good idea, although we might want to think about how/whether to share some routine code, like disk I/O outside of INT 13h, and the ongoing code maintenance issues. But for now, it will help a lot keeping the other targets minimal.

The reference BIOS will allow routines to be removed from rom-elks.c, which I will do, to keep it strictly dependent on what ELKS uses. 

The trace filter looks very interesting: does it just show instruction tracing that hasn't occurred before?

Thanks!

**Comment by mfld-fr** [comment]
> The trace filter looks very interesting: does it just show instruction tracing that hasn't occurred before?

When trying to find out what was wrong with the FreeDOS boot, I used the trace mode, but I got a ~50 MB trace log, with many iterations on the same instructions, resulting in ~1 M lines to analyze. So I applied that filter that makes the instruction to be printed only time. For example, REP MOVS is printed once, even if CX contains a large value.

The resulting log after filtering was ~ 80 KB, so easier to analyze. By the way, I also saw that one could easily output the assembly code by just sorting the trace log.

**Comment by ghaerr** [comment]
The trace filter sounds promising. I will play around with it after it's finished. It has a command line option, right?

> For example, REP MOVS is printed once, even if CX contains a large value.

It is still interesting to trace instructions without the new filter. But I've been thinking that all REP instructions may want to, by default, not show repeated execution. This saves lots of time when single stepping through code that is moving data around, such as the f/memcpy routines in ELKS.

**Comment by mfld-fr** [comment]
Added filter option and make `con_put_char` more portable in latest commit

**Comment by ghaerr** [comment]
Looks good, thanks for adding BIOS Console fixes to reference BIOS.

Maybe commit this now, since it is getting kind of large and API changed for con_put_char. This will allow me to continue working on getting EGA text color modes implemented and test overall PR changes on ELKS.

**Pull request merged**
