### PR TITLE
Add CPU - PLATFORM - BOARD triplet

### PR DESCRIPTION
**Pull request by mfld-fr**
Prepare the integration of the 8018X - 8018X - OR556 configuration.

### CODE REVIEW

**Comment by ghaerr** [comment]
Nice idea about combining CPU, PLATFORM and BOARD to produce TARGET. Using BOARD is clearer also.

I will think a bit about how ELKS might use some combination to produce TARGET as well. I don't think ELKS needs three parameters to TARGET, possibly ARCH and FIRMWARE => TARGET. 

Perhaps here use FIRMWARE=ELKSBIOS, FIRMWARE=PCBIOS, or something like that. ELKS could use FIRMWARE=BIOS or FIRMWARE=ADVTECH, etc.

**Comment by mfld-fr** [comment]
In fact this is not my idea, but just the common practice in the embedded. I just copied... :laughing:

**Comment by ghaerr** [comment]
I find "8xxx" confusing, used as PLATFORM name (and filename). What is it?

**Comment by mfld-fr** [comment]
This is the Intel 8 bits chipset family.

**Pull request merged**
