### PR TITLE
[rom] BIOS extension support

### PR DESCRIPTION
**Pull request by mfld-fr**
Add support of BIOS extension (typically the ELKS kernel in ROM version), as specified by @tkchia in https://github.com/jbruchon/elks/pull/883#issuecomment-735232043.

Redirect to disk boot whenever no BIOS extension detected, through INT FEh.

### CODE REVIEW

**Comment by ghaerr** [comment]
Thank you, I will test this with the latest ELKS which should produce a compatible option ROM image.

**Comment by mfld-fr** [comment]
Sanity tested with 'emu86.sh' without the '-x' option.

**Comment by ghaerr** [comment]
Hello @mfld-fr,

I have tested this with emu86-rom.config (without -x option), emu86-rom-full.config (without -x option), and emu86-disk.config (disk boot), and all operate properly. I will update emu86.sh to remove the special -x entry point after this is committed.

Thank you!

**Comment by mfld-fr** [comment]
@ghaerr : Thanks for the testing on the client side !

**Pull request merged**
