### PR TITLE
Timer interrupt revision

### PR DESCRIPTION
**Pull request by mfld-fr**
- Move dummy timer for ELKS to the right place
- Add edge triggered mode to interrupt controller
- Add EOI paths for ELKS target

### CODE REVIEW

**Comment by ghaerr** [comment]
Thanks @mfld-fr.

Question: since timer_proc() is called every instruction cycle, if the timer reaches 20,000 while a REP or SEG instruction is being emulated, it seems that the interrupt request will not be handled (until seg_none() && rep_none()). Meanwhile, the next iteration's calling of timer_proc will reset the interrupt line back from 1 to 0. Will that previous timer interrupt request get executed, or will it be delayed until the next time the timer reaches 20,000? I don't fully understand the interrupt processing code yet.

Thanks!

**Comment by ghaerr** [comment]
Once committed, I'll also test this with a big update I just made at ELKS (https://github.com/jbruchon/elks/pull/893) which provides support for simultaneous ROMFS and the BIOS INT 13h emulation to allow disk and ROM filesystems to work simultaneously in ROM and on EMU86. Both should work with the option ROM BIOS extension recognition in the next version of EMU86.

I've also found that some problems in ELKS relating to the setup data segment not being initialized, as well as no BIOS Data Area (address 0x0400:0000) in embedded systems. I don't think EMU86 wants to get in the business of emulating the BDA, and merely clearing the setup data segment doesn't initialize some areas written by the boot sector loader when executed. These can be discussed in a separate issue, if required.

**Comment by mfld-fr** [comment]
@ghaerr : You are right. The timer interrupt line could return to inactive during a prefixed instruction, and the processor would not  be interrupted just after that instruction. This is because the interrupt controller emulation has no edge triggered mode yet. That mode will be added in a next commit.

The current processor emulation is correct after adding the (rep_none && seg_none) condition : on a real 80x86 (at least the clone on my SBC), the REPeated instruction is fully executed before the INT pin is sampled.

**Comment by mfld-fr** [comment]
Just added edge triggered mode to the interrupt controller emulation.

**Comment by ghaerr** [comment]
Thanks, would you like me to test this on ELKS before commit?

**Comment by mfld-fr** [comment]
Sanity tested on 'emu86-rom.config'.

**Comment by ghaerr** [comment]
> Sanity tested on 'emu86-rom.config'.

Do you mean tested with that configuration on the latest ELKS tree?

I just built ELKS using the emu86-rom.config, as well as emu-rom-full.config, and while both boot, neither responds to the shell prompt with this PR. I have not had time to look into this yet, but of course suspect that the timer interrupt isn't firing, which is required for the BIOS INT 16h keyboard polling to work. The same kernel boots and runs with the original EMU86.

**Comment by mfld-fr** [comment]
Sorry, tested actually with the wrong payload. It does not work with the latest mainstream ELKS because there is no EOI in the BIOS INT8 stub, and also no I/O port to make that EOI from both that stub or `irqtab.S`.

**Comment by ghaerr** [comment]
>. It does not work with the latest mainstream ELKS because there is no EOI in the BIOS INT8 stub, and also no I/O port to make that EOI from both that stub or irqtab.S.

I added a case entry for the 8259 EOI when I added the IN/OUT monitoring (displayed when at info level 4) last week to io-elks.c:
```
int io_write_byte (word_t p, byte_t b)
    {   
    switch (p) 
        {       
        case 0x20:      // 8259 EOI     
            break;      
        default:
            if (info_level & 4) printf("[OUTB %3xh AL %0xh]\n", p,  b);
        }       
    return 0;
    }   
```
Is this where we need to add the EOI callback to the ELKS timer? If you give me some input as to how you'd like that callback handled, I can add and test it.

**Comment by mfld-fr** [comment]
Rebased and completed the EOI paths, but still have to test on the latest ELKS.

**Comment by mfld-fr** [comment]
Just tested with the latest ELKS with `emu86-rom.config`, no more hang in ASH:
```
mfld@home /mnt/data/home/mfld/advantech/elks-upstream $ emu86 -w 0xe0000 -f elks/arch/i86/boot/Image -w 0x80000 -f image/romfs.bin
info: load address E0000h
info: load file elks/arch/i86/boot/Image
info: file size=10000h
success: file loaded
info: load address 80000h
info: load file image/romfs.bin
info: file size=2C1A9h
success: file loaded

ELKS Setup Headless console
PC/AT class machine, NEC V20 CPU, 512K base RAM.
ELKS kernel 0.4.0 (31456 text, 0 ftext, 3872 data, 37824 bss, 23840 heap)
Kernel text at e062:0000, data 80:0000, top 8000, 446K free
VFS: Mounted root 0x0600 (romfs filesystem).
No init - running /bin/sh
# pwd
/
# ls -l
dr-xr-xr-x  1 root     root           76  Jan 01 1970  .
dr-xr-xr-x  1 root     root           76  Jan 01 1970  ..
dr-xr-xr-x  1 root     root          296  Jan 01 1970  bin
-r-xr-xr-x  1 root     root          232  Jan 01 1970  bootopts
dr-xr-xr-x  1 root     root          303  Jan 01 1970  dev
dr-xr-xr-x  1 root     root           95  Jan 01 1970  etc
dr-xr-xr-x  1 root     root            9  Jan 01 1970  home
dr-xr-xr-x  1 root     root           24  Jan 01 1970  lib
dr-xr-xr-x  1 root     root            9  Jan 01 1970  mnt
dr-xr-xr-x  1 root     root            9  Jan 01 1970  root
dr-xr-xr-x  1 root     root            9  Jan 01 1970  tmp
dr-xr-xr-x  1 root     root           15  Jan 01 1970  var
# 
```

@ghaerr : are you OK to merge this PR ?

**Comment by ghaerr** [comment]
> are you OK to merge this PR ?

Go ahead, EMU86 runs with all three emu86-\*.config configurations now.

**Pull request merged**
